"use client";

import { useEffect, useState, useRef } from "react";
import "./motion.module.css";
import "./kiravo-complete.css";

type Status = "idle" | "generating" | "done" | "error";
type Project = { id:string; prompt:string; url?:string; createdAt:string; aspectRatio:string; style:string; duration:number; model:string };
const examples=["A cinematic drone shot flying over Hyderabad at sunset, warm light, realistic city details","A tiny robot discovering a glowing forest at midnight, volumetric light, gentle camera movement","Luxury car commercial on a rain-soaked neon street, premium reflections, slow motion"];
const models=[{id:"ltx-2.3",label:"LTX 2.3",note:"Fast · audio"},{id:"wan-2.2",label:"Wan 2.2",note:"Detailed"}];
const ratios=["16:9","9:16","1:1"],styles=["Cinematic","Realistic","Anime","Commercial","Dreamy"],ltxDurations=[1,2,3,4,5,6,7,8,9,10,15,20,25,30],wanDurations=[3,4,5,6,7,8,9,10,15];
const nav=["Studio","Director","History","Explore","Settings"];
export default function Home(){
 const [active,setActive]=useState("Studio"),[prompt,setPrompt]=useState(""),[status,setStatus]=useState<Status>("idle"),[error,setError]=useState(""),[renderStage,setRenderStage]=useState("Starting your render…"),[videoUrl,setVideoUrl]=useState(""),[model,setModel]=useState("ltx-2.3"),[aspectRatio,setAspectRatio]=useState("16:9"),[style,setStyle]=useState("Cinematic"),[duration,setDuration]=useState(1),[audio,setAudio]=useState(false),[history,setHistory]=useState<Project[]>([]),[scenes,setScenes]=useState<string[]>([]);
 const pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const durationOptions=model==="wan-2.2"?wanDurations:ltxDurations; const estimatedCredits=duration*24;
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("kiravo-history")||"[]"));}catch{setHistory([])}return()=>{if(pollTimer.current)clearTimeout(pollTimer.current)}},[]);
 useEffect(()=>{if(!durationOptions.includes(duration))setDuration(durationOptions[0]);if(model==="wan-2.2")setAudio(false)},[model]);
 useEffect(()=>{const root=document.documentElement;let raf=0,tx=0,ty=0,cx=0,cy=0;const paint=()=>{cx+=(tx-cx)*.1;cy+=(ty-cy)*.1;root.style.setProperty("--kiravo-mx",cx.toFixed(2));root.style.setProperty("--kiravo-my",cy.toFixed(2));raf=requestAnimationFrame(paint)};const move=(e:PointerEvent)=>{tx=(e.clientX/window.innerWidth-.5)*2;ty=(e.clientY/window.innerHeight-.5)*2};const reset=()=>{tx=0;ty=0};window.addEventListener("pointermove",move,{passive:true});window.addEventListener("pointerleave",reset,{passive:true});raf=requestAnimationFrame(paint);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerleave",reset);cancelAnimationFrame(raf)}},[]);
 const saveHistory=(item:Project)=>setHistory(cur=>{const next=[item,...cur.filter(x=>x.url!==item.url)].slice(0,12);localStorage.setItem("kiravo-history",JSON.stringify(next));return next});
 async function waitForVideo(id:string){const started=Date.now();while(Date.now()-started<900000){const r=await fetch(`/api/generate/status?id=${encodeURIComponent(id)}`,{cache:"no-store"}),data=await r.json();if(!r.ok)throw new Error(data.error||"Could not check the render status.");if(data.status==="complete"&&data.url){setVideoUrl(data.url);setStatus("done");saveHistory({id,prompt:prompt.trim(),url:data.url,createdAt:new Date().toISOString(),aspectRatio,style,duration,model});return}if(data.status==="error"||data.status==="canceled")throw new Error(data.error||"The render did not complete.");setRenderStage(data.status==="queued"?"Your render is queued…":"Rendering your world…");await new Promise<void>(resolve=>{pollTimer.current=setTimeout(resolve,3000)})}throw new Error("The render is taking longer than expected. Please try again.")}
 async function generate(){const value=prompt.trim();if(!value||status==="generating")return;setStatus("generating");setError("");setVideoUrl("");setRenderStage("Starting your render…");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:value,model,aspectRatio,style,duration,audio})}),data=await r.json();if(!r.ok||!data.id)throw new Error(data.error||"KIRAVO could not start the video.");await waitForVideo(data.id)}catch(e){if(pollTimer.current)clearTimeout(pollTimer.current);setError(e instanceof Error?e.message:"Something went wrong.");setStatus("error")}}
 function makeDirector(){const p=prompt.trim()||"your idea";setScenes([`Opening — establish the world and mood around ${p}.`,`Main moment — reveal the subject with controlled cinematic movement.`,`Final shot — resolve the story with a memorable composition.`])}
 return <main className="shell"><div className="floating-scene" aria-hidden="true"><div className="float-orb orb-one"/><div className="float-orb orb-two"/><div className="float-ring ring-one"/><div className="float-ring ring-two"/><div className="float-slab slab-one"><span>K</span><small>WORLD 01</small></div><div className="float-slab slab-two"><span>✦</span><small>CREATE</small></div></div>
 <nav className="nav"><div className="brand"><span className="brand-mark">K</span><span>KIRAVO</span></div><div className="nav-links">{nav.slice(0,4).map(n=><button key={n} className="nav-link-button" onClick={()=>setActive(n)}>{n}</button>)}</div><button className="ghost" onClick={()=>setActive("Settings")}>Settings</button></nav>
 <section className="hero"><div className="eyebrow"><span className="pulse"/> AI CREATIVE STUDIO · {active.toUpperCase()}</div>
 {active==="Studio"&&<><h1>Turn an idea into<br/><em>a world.</em></h1><p className="sub">KIRAVO turns a simple thought into cinematic direction, scenes, motion and visual stories — across desktop, laptop, tablet and mobile.</p><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the video you imagine…" rows={3} disabled={status==="generating"}/><div className="controls"><label>Model<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.label} · {m.note}</option>)}</select></label><label>Frame<select value={aspectRatio} onChange={e=>setAspectRatio(e.target.value)}>{ratios.map(r=><option key={r}>{r}</option>)}</select></label><label>Style<select value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(s=><option key={s}>{s}</option>)}</select></label><label>Length<select value={duration} onChange={e=>setDuration(+e.target.value)}>{durationOptions.map(d=><option key={d} value={d}>{d}s · ~{d*24} credits</option>)}</select></label><button className={`toggle ${audio?"on":""}`} onClick={()=>setAudio(v=>!v)} disabled={status==="generating"||model==="wan-2.2"}>{audio?"●":"○"} Audio{model==="wan-2.2"?" · N/A":""}</button></div><div className="composer-bottom"><div className="chips"><span>{aspectRatio}</span><span>{duration}s</span><span>{style}</span><span>~{estimatedCredits} credits</span></div><button className="generate" onClick={generate} disabled={!prompt.trim()||status==="generating"}>{status==="generating"?"Creating…":"Generate"} <span>↗</span></button></div></div><div className="suggestions"><span>Try an idea</span>{examples.map(x=><button key={x} onClick={()=>setPrompt(x)}>{x}</button>)}</div>{status==="generating"&&<div className="result-card"><div className="result-orb"/><div><strong>{renderStage}</strong><p>KIRAVO is rendering with the real video engine. Keep this tab open while the job completes.</p></div><span className="ready">RENDERING</span></div>}{status==="error"&&<div className="result-card error-card"><div className="result-orb"/><div><strong>Generation failed.</strong><p>{error}</p></div><button className="retry" onClick={generate}>Retry</button></div>}{status==="done"&&videoUrl&&<div className="video-result"><div className="video-head"><div><span className="eyebrow">YOUR KIRAVO WORLD</span><h2>Rendered in <em>motion.</em></h2></div><span className="ready">{duration} SEC · {aspectRatio}</span></div><video src={videoUrl} controls autoPlay playsInline className={`generated-video ratio-${aspectRatio.replace(":","-")}`}/><div className="video-actions"><a className="download" href={videoUrl} target="_blank" rel="noreferrer">Open video ↗</a><button className="retry" onClick={()=>{setStatus("idle");setVideoUrl("")}}>Create another</button></div></div>}</>}
 {active==="Director"&&<div className="feature-panel"><h2>Shape the story before you render.</h2><p className="sub">Turn one prompt into editable cinematic shots.</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe your story…"/><button className="generate" onClick={makeDirector}>Build scene plan ↗</button><div className="director-scenes">{scenes.map((s,i)=><article key={i}><span>0{i+1}</span><div><b>{s.split(" — ")[0]}</b><p>{s.split(" — ")[1]}</p></div></article>)}</div></div>}
 {active==="History"&&<div className="feature-panel"><h2>Recent <em>worlds.</em></h2><p className="sub">Your latest real renders stay available in this browser.</p>{history.length?<div className="history-grid">{history.map(x=><article key={x.id}><video src={x.url} muted playsInline controls preload="metadata"/><div><span className="history-meta">{x.model} · {x.aspectRatio} · {x.style} · {x.duration}s</span><p>{x.prompt}</p><a href={x.url} target="_blank" rel="noreferrer">Open ↗</a></div></article>)}</div>:<div className="empty-state">No renders yet. Create your first world in Studio.</div>}</div>}
 {active==="Explore"&&<div className="feature-panel"><h2>From thought to <em>motion.</em></h2><p className="sub">Imagine. Direct. Create.</p><div className="cards"><article><span className="number">01</span><div className="icon">✦</div><h3>Imagine</h3><p>Describe subject, setting, mood and camera language.</p></article><article><span className="number">02</span><div className="icon">◈</div><h3>Direct</h3><p>Choose model, frame, style, duration and audio.</p></article><article><span className="number">03</span><div className="icon">↗</div><h3>Create</h3><p>Render through the real server-side video engine.</p></article></div></div>}
 {active==="Settings"&&<div className="feature-panel"><h2>Workspace <em>settings.</em></h2><p className="sub">Responsive web workspace with server-side video credentials.</p><div className="settings-grid"><div><label>Display name<input placeholder="KIRAVO creator"/></label><label>Email<input type="email" placeholder="you@example.com"/></label></div><div className="settings-status"><div><span>Video engine</span><b>Connected</b></div><div><span>Responsive web</span><b>Desktop · Tablet · Mobile</b></div><div><span>Generation</span><b>Magic Hour</b></div></div></div></div>}
 </section><footer><div className="brand"><span className="brand-mark">K</span><span>KIRAVO</span></div><span>Make something nobody has seen before.</span><span>© 2026 KIRAVO</span></footer></main>;
}
