"use client";

import { useMemo, useState } from "react";

type Idea = { title: string; prompt: string; style: string; ratio: string; icon: string };
const ideas: Idea[] = [
  { title: "Neon city after rain", prompt: "A cinematic night drive through a futuristic neon city after rain, reflections on wet streets, slow camera movement, atmospheric lighting", style: "Cinematic", ratio: "16:9", icon: "✦" },
  { title: "Dreamlike desert", prompt: "A surreal golden desert with enormous floating arches at sunset, wind moving fine sand, elegant slow aerial camera", style: "Dreamy", ratio: "16:9", icon: "◇" },
  { title: "Anime sky journey", prompt: "A young traveler crossing a glowing sky bridge above the clouds, expressive anime environment, sunrise, sweeping camera", style: "Anime", ratio: "9:16", icon: "☾" },
  { title: "Future product film", prompt: "A premium product reveal on a sculptural dark stage, precise studio lighting, macro details, polished commercial cinematography", style: "Commercial", ratio: "1:1", icon: "◎" },
  { title: "Ocean from above", prompt: "Aerial journey above deep blue ocean waves surrounding a tiny island, natural sunlight, realistic documentary cinematography", style: "Realistic", ratio: "16:9", icon: "△" },
  { title: "Midnight garden", prompt: "A mysterious midnight garden illuminated by thousands of tiny lights, flowers opening in time-lapse, magical camera drift", style: "Dreamy", ratio: "9:16", icon: "✧" }
];

export default function ExplorePage() {
  const [query, setQuery] = useState("");
  const [copied, setCopied] = useState("");
  const visible = useMemo(() => ideas.filter(i => `${i.title} ${i.prompt} ${i.style}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const useIdea = (idea: Idea) => { localStorage.setItem("kiravo-remix-prompt", idea.prompt); localStorage.setItem("kiravo-remix-style", idea.style); localStorage.setItem("kiravo-remix-ratio", idea.ratio); window.location.href = "/"; };
  const copy = async (idea: Idea) => { try { await navigator.clipboard.writeText(idea.prompt); setCopied(idea.title); setTimeout(() => setCopied(""), 1600); } catch {} };
  return <main className="explore-page"><style>{`
    .explore-page{min-height:100vh;background:radial-gradient(circle at 50% -15%,#392064 0,#100a1d 42%,#05040a 84%);color:#fff;font-family:Inter,system-ui,sans-serif;padding:28px}.explore-page *{box-sizing:border-box}.explore-top{max-width:1200px;margin:auto;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ffffff14;padding-bottom:20px}.explore-brand{display:flex;gap:10px;align-items:center;font-weight:900;letter-spacing:.16em}.explore-mark{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;border:1px solid #ffffff20;background:#ffffff10}.explore-back{color:#d9d0e0;text-decoration:none;border:1px solid #ffffff18;background:#ffffff08;border-radius:999px;padding:10px 15px;font-size:11px}.explore-main{max-width:1200px;margin:42px auto 80px}.explore-kicker{font-size:9px;letter-spacing:.25em;color:#78efff}.explore-title{font:400 clamp(45px,7vw,78px)/.9 Georgia,serif;letter-spacing:-.06em;margin:12px 0}.explore-title em{font-style:italic;background:linear-gradient(90deg,#55f5ff,#9c70ff,#ff58c9);-webkit-background-clip:text;color:transparent}.explore-sub{max-width:560px;color:#93889f;font-size:13px;line-height:1.6}.explore-tools{margin:28px 0;display:flex;gap:10px}.explore-search{width:100%;border:1px solid #ffffff18;border-radius:14px;background:#ffffff08;color:#fff;padding:14px 16px;outline:none}.explore-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.idea-card{border:1px solid #ffffff16;border-radius:22px;background:#ffffff08;overflow:hidden}.idea-art{height:190px;display:grid;place-items:center;background:radial-gradient(circle at 50% 40%,#3a2460,#0a0710 70%);position:relative}.idea-art b{font:400 70px Georgia;color:#dcd0ef}.idea-art small{position:absolute;top:12px;left:12px;border:1px solid #ffffff20;background:#080611aa;padding:6px 9px;border-radius:999px;font-size:8px;color:#bdb3c8}.idea-body{padding:16px}.idea-body h2{font-size:16px;margin:0}.idea-body p{font-size:10px;line-height:1.5;color:#887d93;min-height:46px}.idea-meta{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.idea-meta span{font-size:8px;padding:5px 8px;border-radius:999px;background:#ffffff08;border:1px solid #ffffff10;color:#aaa0b1}.idea-actions{display:flex;gap:7px}.idea-actions button{flex:1;border:1px solid #ffffff18;background:#ffffff07;color:#ddd5e2;border-radius:9px;padding:10px 6px;font-size:9px;cursor:pointer}.idea-actions .use{background:#fff;color:#08050d;border-color:#fff;font-weight:900}.empty{text-align:center;border:1px dashed #ffffff20;border-radius:20px;padding:60px;color:#85798e}@media(max-width:900px){.explore-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.explore-page{padding:16px}.explore-grid{grid-template-columns:1fr}.idea-art{height:220px}}
  `}</style><header className="explore-top"><div className="explore-brand"><span className="explore-mark">K</span><span>KIRAVO</span></div><a className="explore-back" href="/">← Studio</a></header><section className="explore-main"><div className="explore-kicker">KIRAVO · DISCOVERY</div><h1 className="explore-title">Find your next <em>world.</em></h1><p className="explore-sub">Explore ready-to-use creative directions. Borrow a prompt, remix it in Studio, or copy it as a starting point for your own idea.</p><div className="explore-tools"><input className="explore-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, styles or scenes…"/></div>{visible.length ? <div className="explore-grid">{visible.map(i=><article className="idea-card" key={i.title}><div className="idea-art"><b>{i.icon}</b><small>{i.style} · {i.ratio}</small></div><div className="idea-body"><h2>{i.title}</h2><p>{i.prompt}</p><div className="idea-meta"><span>{i.style}</span><span>{i.ratio}</span></div><div className="idea-actions"><button onClick={()=>copy(i)}>{copied===i.title?"Copied ✓":"Copy prompt"}</button><button className="use" onClick={()=>useIdea(i)}>Use idea →</button></div></div></article>)}</div> : <div className="empty">No ideas match that search.</div>}</section></main>;
}
